package com.oauth2.mapper;

import com.oauth2.entity.SysRequestPathPermission;
import com.oauth2.entity.SysRequestPathPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRequestPathPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_request_path_permission
     *
     * @mbg.generated
     */
    long countByExample(SysRequestPathPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_request_path_permission
     *
     * @mbg.generated
     */
    int deleteByExample(SysRequestPathPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_request_path_permission
     *
     * @mbg.generated
     */
    int insert(SysRequestPathPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_request_path_permission
     *
     * @mbg.generated
     */
    int insertSelective(SysRequestPathPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_request_path_permission
     *
     * @mbg.generated
     */
    List<SysRequestPathPermission> selectByExample(SysRequestPathPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_request_path_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysRequestPathPermission record, @Param("example") SysRequestPathPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_request_path_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysRequestPathPermission record, @Param("example") SysRequestPathPermissionExample example);
}